[tox]
envlist = lint
isolated_build = true

[testenv:lint]
skip_install = true
deps = ruff
commands =
    ruff format --diff src/uqphonon
    ruff check src/uqphonon

[testenv:format]
skip_install = true
deps = ruff
commands =
    ruff format src/uqphonon
    ruff check --fix-only src/uqphonon
