[tox]
envlist = lint
isolated_build = true

[testenv:lint]
skip_install = true
deps = ruff
commands =
    ruff check src/pet_phonons
    ruff format --check src/pet_phonons

[testenv:format]
skip_install = true
deps = ruff
commands =
    ruff check --fix src/pet_phonons
    ruff format src/pet_phonons
