[tox]
envlist = lint
isolated_build = true

[testenv:lint]
skip_install = true
deps = ruff
commands =
    ruff check src/petphonon
    ruff format --check src/petphonon

[testenv:format]
skip_install = true
deps = ruff
commands =
    ruff check --fix src/petphonon
    ruff format src/petphonon
